### ISSUE TITLE
Better error handling for server side

### ISSUE THREAD

**Issue by ankan20** [sujaltangde/JobLane#13]
I want to add some logics for better error handling in server side .

Please assign to me this under GSSOC 2024
@sujaltangde

**Comment by haard18** [comment]
Hey Assign me this issue! I am GSSOC'24 Contributor
@sujaltangde

**Comment by ankan20** [comment]
@sujaltangde Please assign me this issue under GSSOC 2024

**Comment by omneaa** [comment]
HI
 I am a GSSoC'24 contributor 
I can do this and i will use nodejs  
I'd be happy if you assign it to me

**Comment by sujaltangde** [comment]
Hey, @ankan20 I have assigned you this issue, you can start work on it.

**Comment by ankan20** [comment]
Thanks I will finish it soon. @sujaltangde
