### ISSUE TITLE
Revamping Footer Design

### ISSUE THREAD

**Issue by Niharika0104** [sujaltangde/JobLane#20]
#### Description:
Our project aims to redesign the footer section to ensure responsiveness across all screen sizes, prioritizing seamless navigation and user engagement. Below are the specific issues to address:

#### Issues:
1. **Responsive Layout Issue:** The current footer design lacks responsiveness, causing alignment and layout issues on different screen sizes.
   - **Steps to Reproduce:**
     1. Open the website on various devices with different screen sizes (desktop, tablet, mobile).
     2. Navigate to any page with the footer section.
     3. Observe how the footer elements behave and whether they adapt well to different screen sizes.
   - **Expected Behavior:** The footer should adjust its layout and content to fit appropriately on all screen sizes without causing any misalignment or overlap.

**Comment by VishalGaurav01** [comment]
Excited to work on this issue and want to contribute more to the project.
![image](https://github.com/sujaltangde/JobLane/assets/97465452/09fd6779-24b5-4b65-a67b-8e1c30266faa)
This is a footer responsive design that will navigate throughout the website
Assignee: Assign this issue to me...looking for a more impactful contribution to this website.

**Comment by Niharika0104** [comment]
@VishalGaurav01 Can you please open another issue as I want to work on that? We are supposed to open our own issues and get them assigned to us.🙂

**Comment by VishalGaurav01** [comment]
Ok, @Niharika0104! I thought the admin had mentioned this issue.

**Comment by Niharika0104** [comment]
No issues.The admin for this project is @sujaltangde and who ever owns the project he/she will be admin check the name who opens the issue if it is project admin then get it assigned to you.All the best

**Comment by sujaltangde** [comment]
Don't worry guys, everyone will the get issues assigned, Currently I am dealing with the end sem exams and busy in that, I will start work on this project in 2-3 days, until then you guys can go through code and open issues which you found.

**Comment by sujaltangde** [comment]
Hey, @Niharika0104 I assigned you this issue, you can continue working on it
