### ISSUE TITLE
Improve filter

### ISSUE THREAD

**Issue by siddxharth1** [sujaltangde/JobLane#27]
we can remove the apply search button and directly apply the filter when we click on the button its self and i would like to create a single filter for Categories,  Companies and salary. And in the salary we have to define the fix salary  i will create a range filter in which user will give a range of salary he wants
can you assign me this issue under gssoc

**Comment by Krishnabhattacharya** [comment]
so for that we have to make route(APIs) for filtering ?

**Comment by siddxharth1** [comment]
No i will use filter function to filter out the jobs matches the filter option

**Comment by sujaltangde** [comment]
Hey, @siddxharth1 I have assigned you this task, you can start work on it.
