### ISSUE TITLE
Missing CONTRIBUTING.md File in Repository

### ISSUE THREAD

**Issue by suhanipaliwal** [sujaltangde/JobLane#33]
The repository currently lacks a CONTRIBUTING.md file, which is an important resource for guiding potential contributors on how to engage with the project effectively. A CONTRIBUTING.md file outlines the contribution guidelines, coding standards, and procedures for submitting pull requests, thus streamlining the contribution process and ensuring consistency across contributions.

Could you please assign this issue to me under GSSOC 24.

**Comment by Anumallasarayu123** [comment]
Can U please assign me the issue under GSSOC 24. I already raised PR can u please check and assign me the issue. Don't forget to add labels.

**Comment by sujaltangde** [comment]
Hey, @suhanipaliwal , can you enhance the contributing.md file, and make it more readable and user friendly, I have assigned this issue to you.
