### ISSUE TITLE
Typo Correction and Address Formatting on Contact Tab

### ISSUE THREAD

**Issue by nehashekhawat255** [sujaltangde/JobLane#34]
I've spotted a couple of issues on our website's "Contact" tab:

- **Address Format:** The address should appear as a single block of text, not as bullet points.

- **Typo:** In the FAQs, "crate" should be corrected to "create" in the question about account creation.

- **Duplicate Question:** There's a repeated question about account creation. I suggest replacing one instance with "How can I check the status of my job application?"

Can you please assign this issue to me. I'm a GSSoC'24 contributor eager to assist.

**Comment by Karankumar2004** [comment]
Dear @sujaltangde, I'm keen to contribute. Could you assign me this issue under GSSoc 24'?

**Comment by sujaltangde** [comment]
Issue was fixed by @nehashekhawat255 , Thank you for your contribution, I am closing the issue now
