### ISSUE TITLE
Feature: Filter genuine email

### ISSUE THREAD

**Issue by pankaj-bind** [sujaltangde/JobLane#43]
## Security Feature
In your application anyone can enter using **temporary or disposable email**.
I will add a feature so that no one could create an account using **temporary or disposable email**.
It will allow only genuine users in your database.
It will help to avoid any bot.
Assign me this work under GSSoC24, I will implement it.

**Comment by sujaltangde** [comment]
@pankaj-bind Okay, go for it

**Comment by gopalepic** [comment]
@pankaj-bind  did you implemented the feature into the codebase
