### ISSUE TITLE
Enhancement : making cards under Featured Job section more user interactive.

### ISSUE THREAD

**Issue by Sudhanshu2306** [sujaltangde/JobLane#57]
![image](https://github.com/sujaltangde/JobLane/assets/126086429/e53d7b1f-2521-4b0e-9a4c-723de0d049db)

On hovering no change or response in cards. Adding proper styling can make it more appealing.

**Comment by Sudhanshu2306** [comment]
@sujaltangde please assign me this issue, I will make the card more user interactive. Thank You!

**Comment by sujaltangde** [comment]
Okay @Sudhanshu2306 go for it.

**Comment by Sudhanshu2306** [comment]
I have made a pr, with some insertions, please see if some changes are still needed. Thank You!
