### ISSUE TITLE
Add 404-Notfound page

### ISSUE THREAD

**Issue by DharshiBalasubramaniyam** [sujaltangde/JobLane#69]
When a user tries to access a page that does not exist, the application does not display a proper error message. Instead, the current behavior is as shown in the following screenshot:

![image](https://github.com/sujaltangde/JobLane/assets/139672976/642c3bb8-7383-451f-a461-2f201d3eb244)

Proposed Improvement:

To enhance the user experience, we can display a more informative and user-friendly error message. The proposed design is shown below:

![Screenshot 2024-05-14 202146](https://github.com/sujaltangde/JobLane/assets/139672976/d6c76bf4-f1b3-4ee6-9b1e-3e3f1e2d2458)

Kindly assign this issue to me so that I can implement the proposed solution and improve the user experience when encountering a 'page not found' error.

**Comment by sujaltangde** [comment]
@DharshiBalasubramaniyam, You can work on it, I have assigned it to you, but make sure to make the ui in dark theme which should match the existing pages ui, and use tailwind css for styling.
