### ISSUE TITLE
Designing Contact page and About Page

### ISSUE THREAD

**Issue by Prithwi32** [sujaltangde/JobLane#7]
Key points achieved by this contribution:
*Improving UIUX of Contact page
*Improving UIUX of About page
*Responsiveness

**Comment by Prithwi32** [comment]
@sujaltangde Please could you assign me this issue under GSSoC'24

**Comment by rushiii3** [comment]
@sujaltangde  please assign me this issue

**Comment by IbrahimDev00** [comment]
Having worked on multiple Real world projects, I have a good idea of how to design it.
Please assign it to me.
GSSoc'24 contributor.
Please add labels.

**Comment by agxmbedi** [comment]
I am Agamjot singh. Under GSSOC'24, I would like to work on this issue. Pls assign me this!!

**Comment by VishalGaurav01** [comment]
Already completed my previous assignments. Here i have a responsive design for contact us page and about us.
![image](https://github.com/sujaltangde/JobLane/assets/97465452/daaa5592-6927-43f2-a691-2428d43e3325)
Assignee: Please Assign this issue to me.

**Comment by Prithwi32** [comment]
> Key points achieved by this contribution: *Improving UIUX of Contact page *Improving UIUX of About page *Responsiveness

@sujaltangde may I know y this issue still not assigned? made this issue under gssoc'24
