### ISSUE TITLE
User and admin routes are not protected

### ISSUE THREAD

**Issue by DharshiBalasubramaniyam** [sujaltangde/JobLane#70]
Without logging in, when I try to access admin or user-specific pages, the application redirects me to those pages. This behavior poses a security risk as it allows unauthorized access to sensitive routes. The current scenario is illustrated in the screenshots below:

![Screenshot 2024-05-18 075930](https://github.com/sujaltangde/JobLane/assets/139672976/db151561-eeab-49f0-8ded-fd6d1394416c)

![Screenshot 2024-05-18 080002](https://github.com/sujaltangde/JobLane/assets/139672976/d01139bb-7c27-4d5b-9859-df95e2f92dd6)

To enhance security, we should check both user existence and role before navigating to protected routes. This can be achieved by creating a ProtectedRoute component that handles route protection based on an isAllowed prop. If isAllowed is false, the user will be redirected to a specified path (defaulting to /unauthorized). The proposed behavior is shown below:

![image](https://github.com/sujaltangde/JobLane/assets/139672976/f72cd626-c853-43e2-a8d1-f22206f6512e)

Kindly please assign this issue to me to solve the issue.

**Comment by sujaltangde** [comment]
@DharshiBalasubramaniyam ,You can work on it, I have assigned it to you, but make sure to make the ui in dark theme which should match the existing pages ui, and use tailwind css for styling.
