### ISSUE TITLE
[Bug]: Only one filter is applied at a time

### ISSUE THREAD

**Issue by DhruvChadha22** [sujaltangde/JobLane#77]
**Describe the bug**
Currently, the Category and Salary filter can not be applied together with the Companies filter.

**To Reproduce**
1. Go to the Jobs page.
2. Apply any Category and Salary filter.
3. Apply any Company filter.
4. The filter which you applied last will only be reflected.

**Expected behavior**
When applying both filters, it should reflect the jobs for both the filters in conjunction.

**Screenshots**
![image](https://github.com/sujaltangde/JobLane/assets/153297759/d5dc6c7b-0eee-4a8c-b19a-fa8fdd720b5e)
In the above screenshot, only the Marketing related Job by Google should be shown but since I applied the Company filter last, it only applied that filter and all Jobs by Google are displayed.

**Comment by DhruvChadha22** [comment]
I would like to work on this under GSSOC'24. Please assign it to me after you verify the issue.

**Comment by sujaltangde** [comment]
@DhruvChadha22 , Okay go for it
