### ISSUE TITLE
Login and Register Page Design

### ISSUE THREAD

**Issue by Prithwi32** [sujaltangde/JobLane#8]
Key points achieved by this contribution:
*Improving UIUX of Login page
*Improving UIUX of Register page
*Responsiveness

**Comment by agxmbedi** [comment]
I am Agamjot singh. Under GSSOC'24, I would like to work on this issue. Pls assign me this!!

**Comment by KARANSINGH34951** [comment]
The current design of the page is simple and functional, but it lacks visual appeal.


<img width="960" alt="Screenshot 2024-05-10 214540" src="https://github.com/sujaltangde/JobLane/assets/137412876/cff76863-edf5-493b-81bd-491f636aedd6">

I'm open to any suggestions or ideas for improving the "About Us" page and making it a more valuable resource for our website visitors. Assign me these issues by adding the tag of GSSOC'24.

**Comment by Shruti-Sawant** [comment]
I an make  responsive and visually appealing user interfaces that captivate users, particularly for login and registration pages. Assign this task to me, and I'll create a UI that not only attracts users but also ensures a seamless experience across different devices under Gssoc'24
