### ISSUE TITLE
💡[FEATURE]: Auto Commenting feature for PR Merged

### ISSUE THREAD

**Issue by Asymtode712** [sujaltangde/JobLane#91]
**Is your feature request related to a problem? Please describe.**
Yes, the feature request is related to a problem. When pull requests (PRs) are merged in a project, it is often important to provide consistent feedback or notifications to the contributors. Currently, this process can be manual and time-consuming, leading to inconsistent communication and delayed acknowledgments. This can frustrate both maintainers, who have to remember to comment, and contributors, who might feel their efforts are not promptly recognized.

**Describe the solution you'd like**
To enhance our communication and acknowledgment process, we're implementing an auto-commenting feature for specific events within our project repository. This feature will automatically generate comments under the following circumstances:
PR Merged: Upon the successful merging of a pull request (PR), an auto-comment will be added to the corresponding issue, indicating that the PR has been merged and expressing gratitude to the contributor for their valuable contribution.

**What problem is this feature trying to solve?**
This feature aims to solve the problem of inconsistent and delayed communication following the merging of PRs. By automating the commenting process, it ensures that contributors receive timely feedback and acknowledgments. It also reduces the administrative burden on maintainers, allowing them to focus more on code reviews and other critical tasks.

![PR merged](https://github.com/sujaltangde/JobLane/assets/115717746/4488b1eb-8d84-44f2-8db8-d304a4e5ef4f)

@sujaltangde please assign me this issue under gssoc'24

**Comment by sujaltangde** [comment]
@Asymtode712 , Okay go for it

**Comment by Asymtode712** [comment]
@sujaltangde For proper working of this workflow follow the below given steps:

**Step 1: Create a Personal Access Token (PAT) with repo Permission**


**1. Navigate to Settings:**

 - Click on your profile picture in the upper-right corner of the page.
 - Select "Settings" from the dropdown menu.

**2. Go to Developer Settings:**

- In the left sidebar, scroll down and click on "Developer settings."

**3. Create a New Token:**

- Click on "Personal access tokens" in the left sidebar.
- Click on the "Generate new token" button.

**4. Configure the Token:**

- Token Description: Enter a descriptive name for the token (e.g., Repo Access Token).
- Expiration: Set no expiration.
- Select Scopes: Check the box next to repo to grant full control of private repositories.

**5. Generate Token:**

- Scroll down and click on the "Generate token" button.
- Important: Copy the token to a secure location. You will not be able to see it again once you navigate away from the page.
<br>

**Step 2: Assign the Token to GITHUB_TOKEN Environment Variable**

**1. Navigate to Your Repository:**

- Go to your repository on GitHub.
- Click on the "Settings" tab.

**2. Go to Secrets:**

- In the left sidebar, click on "Secrets and variables" and then "Actions".

**3. Create a New Secret:**

- Click on the "New repository secret" button.
- Name: Enter GITHUB_TOKEN.
- Value: Paste your generated token.
- Click on the "Add secret" button.
